### ISSUE TITLE
PagedListRenderOptions does not exist for X.PagedList.Mvc.Core 2.2

### ISSUE THREAD

**Issue by Irusik79** [dncuug/X.PagedList#140]
PagedListRenderOptions does not exist for X.PagedList.Mvc.Core 2.2.

 How can we handle this in Core2.2 version?

**Comment by bluegrounds** [comment]
@Irusik79 Did you find a way to fix this?

**Comment by Irusik79** [comment]
@bluegrounds , nope..

**Comment by tony10819** [comment]
Actually, I found a fix today after struggle for a few days.  I'm not sure it's a bug but it's more by following the official instructions/examples.  I would suggest to update your front page instructions/examples to avoid misleading.  My project is based on MVC.Core 2.2 and VS 2019 Community Edition.   

To make it work accordingly, the following instructions are required:
Controller: 
public IActionResult  Index(int page=1) //Set default to page 1 when it's not specified
{
   var query = _context.Vendor.AsQueryable(); //Return an IQueryable type as a list of vendors.
   return View(query.AsNoTracking().ToPagedList(page, 10)); //To improve speed, load one page directly without saving to a var
}

View:
@model IPagedList<MyApp.Models.Vendor>
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Mvc.Common
...
@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page = page }),
         new PagedListRenderOptions
           {
              DisplayEllipsesWhenNotShowingAllPageNumbers = false,
              LiElementClasses = new string[] { "page-item" },
              PageClasses = new string[] { "page-link" }
           })

Hope this helps.
Have a great day!
Thanks,
Tony Yee

**Comment by ernado-x** [comment]
Should be fixed in this version: https://www.nuget.org/packages/X.PagedList.MVC.Core/7.9.0

**Comment by dunkhi** [comment]
Did anyone find a way to fix this problem with just standard X.PageList.MVC? If you install the mvc package first, it will install all the dependencies, but the PagedListRenderOptions is still missing from the library?
